version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.run

    #command: bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- /usr/local/bundle/bin/rackup -o 0.0.0.0 -p 4567
    command: bundle exec rackup -o 0.0.0.0 -p 4567 & bundle exec rackup -o 0.0.0.0 -p 9292 & sass --watch public/api-docs/css


    environment:
      - RUBY_ENV=development
    ports:
      - "4567:4567"
      - "9292:9292"
      # Debugging ports
      # - "1234:1234"
      # - "26162:26162"
    volumes:
      - .:/external_api

    tty: true
    stdin_open: true