swagger: '2.0'
info:
  title: CareCloud API Endpoints
  description: CareCloud API v2 Interactive Documentation
  version: "2.0.0"
# the domain of the service
# host: localhost:9292
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v2
produces:
  - application/json
paths:
definitions:
