development: &development
  url: <%=ENV['CONFIG_DMS_URL']%>
localhost: 
  *development
qa: 
  url: "https://dms-qa.carecloud.com"
staging: 
  url: "https://dms-staging.carecloud.com"
production: 
  url: "https://dms.carecloud.com"
