development: &development
  url: <%=ENV['CONFIG_DMS_URL']%>
localhost: 
  *development
qa: 
  url: <%=ENV['CONFIG_DMS_URL']%>
staging: 
  url: "https://dms-staging.carecloud.com"
production: 
  url: "https://dms.carecloud.com"
demo:
  url: "http://documents.careclouddemo.com"
