development:
  adapter: mongodb
  host: 10.64.22.131
  port: 27017

production:
  adapter: mongodb
  host: 10.171.1.36
  port: 27017

qa:
  adapter: mongodb
  host: 54.242.195.20
  port: 27017

staging:
  adapter: mongodb
  host: 54.242.195.20
  port: 27017

test:
  adapter: mongodb
  host: 10.64.22.131
  port: 27017

