development:
  probes:
    webservices: http://devservices.carecloud.local/
    dms: https://dms-dev.carecloud.com
    memcache: cc-bl-mcache00-dev.carecloud.local:11211
localhost:
  probes:
    webservices: http://devservices.carecloud.local/
    dms: "https://dms-qa.carecloud.com"
    memcache: cc-bl-mcache00-dev.carecloud.local:11211
qa:
  probes:
    webservices: http://qaservices.carecloud.local/
    dms: "https://dms-qa.carecloud.com"
    memcache: 192.168.123.61:11211
staging:
  probes:
    webservices: https://services-staging.carecloud.com a
    dms: "https://dms-staging.carecloud.com"
    memcache: 192.168.123.61:11211
production:
  probes:
    webservices: https://services.carecloud.com/
    dms: "https://dms.carecloud.com"
    memcache: cc-tm01-mcache00.carecloud.local:11211
