api_internal_svc_url: http://devservices.carecloud.local/
#api_internal_svc_url: http://localservices.carecloud.local:3000/
api_internal_doc_srv_upld_url: http://uploads-dev.carecloud.local/
memcache_servers: 192.168.123.61:11211