# Config File for Solr Full Text Search Engine.  

# For now we need the ability to disable solr if needed.  Change disabled bit per environment to do so.

indexes: &INDEXES
    - class_name: Patient
      index_name: patient
    - class_name: Contact
      index_name: contact
    - class_name: Document
      index_name: document
    - class_name: Payer
      index_name: payer
    - class_name: Diagnosis
      index_name: diagnose
    - class_name: Procedure
      index_name: procedure
    - class_name: ProviderAdjustmentCode
      index_name: provider_adjustment_code
    - class_name: InsuranceAdjustmentCode
      index_name: insurance_adjustment_code
    - class_name: LabRequestVendorTestCode
      index_name: lab_request_vendor_test_code
    - class_name: Specialty
      index_name: speciality
    - class_name: MasterLocation
      index_name: master_location
    - class_name: Physician
      index_name: physician
    - class_name: Claim
      index_name: claim
    - class_name: SnomedICDCode
      index_name: snomed_icd_codes
    
development:
  url: http://devsearch.carecloud.local/
  start_page: 0 # page
  rows: 100 # num results returned per page
  disabled: false
  indexes: *INDEXES

qa:
  url: http://devsearch.carecloud.local/
  start_page: 0 # page
  rows: 100 # num results returned per page
  disabled: false
  indexes:
      - class_name: Patient
        index_name: patient_qa
      - class_name: Contact
        index_name: contact_qa
      - class_name: Document
        index_name: document_qa
      - class_name: Payer
        index_name: payer_qa
      - class_name: Diagnosis
        index_name: diagnose_qa
      - class_name: Procedure
        index_name: procedure_qa
      - class_name: ProviderAdjustmentCode
        index_name: provider_adjustment_code_qa
      - class_name: InsuranceAdjustmentCode
        index_name: insurance_adjustment_code_qa
      - class_name: LabRequestVendorTestCode
        index_name: lab_request_vendor_test_code_qa
      - class_name: Specialty
        index_name: speciality_qa
      - class_name: MasterLocation
        index_name: master_location_qa
      - class_name: Physician
        index_name: physician_qa
      - class_name: Claim
        index_name: claim_qa
      - class_name: SnomedICDCode
        index_name: snomed_icd_codes_qa
  
test:
  disabled: true

batch:
  disabled: true
  indexes: *INDEXES

staging:
  url: http://stagingsearch.carecloud.local/
  start_page: 0 # page
  rows: 100 # num results returned per page
  disabled: false
  indexes: *INDEXES

production:
  url: http://search.carecloud.local/
  start_page: 0 # page
  rows: 100 # num results returned per page
  disabled: true
  indexes: *INDEXES
  
demo:
  url: http://demosearch.carecloud.local/
  start_page: 0 # page
  rows: 100 # num results returned per page
  disabled: false
  indexes:
      - class_name: Patient
        index_name: patient_demo
      - class_name: Contact
        index_name: contact_demo
      - class_name: Document
        index_name: document_demo
      - class_name: Payer
        index_name: payer_demo
      - class_name: Diagnosis
        index_name: diagnose_demo
      - class_name: Procedure
        index_name: procedure_demo
      - class_name: ProviderAdjustmentCode
        index_name: provider_adjustment_code_demo
      - class_name: InsuranceAdjustmentCode
        index_name: insurance_adjustment_code_demo
      - class_name: LabRequestVendorTestCode
        index_name: lab_request_vendor_test_code_demo
      - class_name: Specialty
        index_name: speciality_demo
      - class_name: MasterLocation
        index_name: master_location_demo
      - class_name: Physician
        index_name: physician_demo
      - class_name: Claim
        index_name: claim_demo
