development:
  probes:
    - "dms:critical"
    - "webservice:critical"
    - "mem_cache:critical"
    - "audit:warn"
localhost:
  probes:
    - "dms:critical"
qa:
  probes:
    - "postgres:critical"
staging:
  probes:
    - "postgres:critical"
production:
  probes:
    - "postgres:critical"
