development:
  probes:
    - "dms:critical"
    - "webservice:critical"
    - "mem_cache:critical"
    - "cc_auth:critical"
    - "audit:warn"
localhost:
  probes:
    - "dms:critical"
    - "webservice:critical"
    - "mem_cache:critical"
qa:
  probes:
    - "dms:critical"
    - "webservice:critical"
    - "mem_cache:critical"
    - "audit:warn"
staging:
  probes:
    - "dms:critical"
    - "webservice:critical"
    - "mem_cache:critical"
    - "audit:warn"
production:
  probes:
    - "dms:critical"
    - "webservice:critical"
    - "mem_cache:critical"
    - "audit:warn"
