---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 80, host: 3000 }]
  customize:
    memory: 4056

provisioner:
  name: chef_zero
  environments_path: test/environments
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: ../encrypted_data_bag_secret
  client_rb:
    environment: development

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[rack_server::install]
      - recipe[ccbase::setup]
      - recipe[app_external::default]
      - recipe[app_external::deploy]
    attributes:
      rack_server:
        iteration: 6
      ccbase:
        bundle: true
        config_ctxt_environment: true
        envs:
          CONFIG_SALESFORCE_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/489152718636/salesforce_dev"
          CONFIG_AUTH_URL: "http://auth.development.carecloud.local"
          CONFIG_AUTH_INTERNAL_API_KEY: "pGoDwCvh4xPopUfmZDhpgO0yEQGnv9AG"
          CONFIG_DMS_URL: "http://documents.development.carecloud.local"
          CONFIG_API_INTERNAL_SVC_URL: "http://services.development.carecloud.local/"
          CONFIG_API_INTERNAL_DOC_SRV_UPLD_URL: "http://documents.development.carecloud.local"
          CONFIG_MIRTH_OUTBOUND_SVC_URL: "mirth.development.carecloud.local:8088"
          CONFIG_MIRTH_PRIVATE_KEY: "thisstringshouldbeprivate"
          CONFIG_MIRTH_EDI_TOKEN: "C4r3Cl0ud3D1"
          CONFIG_MIRTH_IP_ADDRESS: "172.124.1.53"
          CONFIG_MEMCACHE_SERVERS: "mcache.development.carecloud.local:11211"
          CONFIG_LAB_USER: "spectra_test"
          CONFIG_LAB_PASS: "MLhYSFoptX58EsSrdAX1iyb3cuPiJMud"
          CONFIG_API_VERSION: "26.2"
          CONFIG_LOGGING_LEVEL: "0"
          CONFIG_SWAGGER_GATEWAY_URL: "https://external-api-gateway.development.carecloud.com"
          CONFIG_SWAGGER_BACKEND_URL: "https://external-api-elb-dev.carecloud.com"
          CONFIG_SWAGGER_NGROK_URL: "http://791b33a7.ngrok.com"
          CONFIG_SWAGGER_CORS_URL: "http://developer.development.carecloud.com"
          CONFIG_SWAGGER_PLATFORM_URL: "https://platform.development.carecloud.com"
