name: 6 - Hotfix Release
on:
  push:
    branches: [ 'release/**' ]

permissions:
  contents: write
  id-token: write

jobs:
  do:
    uses: carecloud/github-actions-workflows-docker-ecr-eks-helm-argocd/.github/workflows/hotfix-release.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      default_branch: master
      tenant: 'plat'
    secrets:
      github-private-actions-pat: "${{ secrets.GHA_REPO_ACCESS_TOKEN }}"
      registry: "${{ secrets.ECR_REGISTRY }}"
      secret-outputs-passphrase: "${{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
      ecr-region: "${{ secrets.ECR_REGION }}"
      ecr-iam-role: "${{ secrets.ECR_IAM_ROLE }}"