json.name document['name']
json.id document['id']
json.handler document['document_handler']
json.format document['document_format']
json.set_id document['document_set_id']
json.source_id document['document_source_id']